#!/bin/bash

#SBATCH -A IscrC_LLAMP
#SBATCH -p boost_usr_prod
#SBATCH --qos boost_qos_lprod
#SBATCH --time 24:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:4
#SBATCH --mem=0
#SBATCH --job-name=run_mimicel
#SBATCH --out=out/run.log
#SBATCH --err=out/run.log

srun ./launch_run_single_exe $1
